version: '3.8'

services:
  cpp-server:
    image: cppwebserver:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Изменили внешний порт на 8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
